main: me.mrliam2614.FacilitisAPI.FacilitisAPI
name: FacilitisAPI
version: 5.0.1
authors: [MrLiam2614, TheLore]
depend: [Vault]
description: API to help new developer on their plugin creation
api-version: 1.16